import { useEffect, useMemo, useState } from 'react'
import wildcatLogo from './assets/wildcat-logo.png'
import { RosterList } from './components/RosterList'
import { SearchBar } from './components/SearchBar'
import { SortControl } from './components/SortControl'
import { searchPlayers } from './lib/searchPlayers'
import { sortPlayers } from './lib/sortPlayers'
import { TEAM } from './team'
import type { Player, SortDirection, SortKey } from './types'

type RosterState = { status: 'loading' } | { status: 'error' } | { status: 'ready'; players: Player[] }

function App() {
  const [roster, setRoster] = useState<RosterState>({ status: 'loading' })
  const [query, setQuery] = useState('')
  const [sortKey, setSortKey] = useState<SortKey>('jersey')
  const [direction, setDirection] = useState<SortDirection>('asc')

  useEffect(() => {
    // roster.json is generated by scripts/build-roster.ts and served from public/
    fetch(`${import.meta.env.BASE_URL}roster.json`)
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`)
        return response.json() as Promise<Player[]>
      })
      .then((players) => setRoster({ status: 'ready', players }))
      .catch(() => setRoster({ status: 'error' }))
  }, [])

  const allPlayers = useMemo(() => (roster.status === 'ready' ? roster.players : []), [roster])
  const players = useMemo(
    () => sortPlayers(searchPlayers(allPlayers, query), sortKey, direction),
    [allPlayers, query, sortKey, direction],
  )

  function handleSortChange(key: SortKey) {
    if (key === sortKey) {
      setDirection((current) => (current === 'asc' ? 'desc' : 'asc'))
    } else {
      setSortKey(key)
      setDirection('asc')
    }
  }

  return (
    <div className="app">
      <header className="app-header">
        <div className="brand">
          <span className="brand-logo">
            <img src={wildcatLogo} alt={`${TEAM.name} logo`} width="256" height="256" />
          </span>
          <div className="brand-text">
            <p className="brand-school">{TEAM.school}</p>
            <h1>
              {TEAM.name} <span className="brand-sport">{TEAM.sport}</span>
            </h1>
            <p className="brand-location">{TEAM.location}</p>
          </div>
        </div>
        <SearchBar value={query} onChange={setQuery} />
        <SortControl sortKey={sortKey} direction={direction} onChange={handleSortChange} />
      </header>
      <main>
        {roster.status === 'loading' && <p className="status">Loading roster…</p>}
        {roster.status === 'error' && <p className="status">Couldn't load the roster. Check your connection and refresh.</p>}
        {roster.status === 'ready' && (
          <>
            <p className="result-count" aria-live="polite">
              {players.length} of {allPlayers.length} players
            </p>
            <RosterList players={players} />
          </>
        )}
      </main>
    </div>
  )
}

export default App
