import { useEffect, useMemo, useState } from 'react'
import wildcatLogo from './assets/wildcat-logo.png'
import { RosterList } from './components/RosterList'
import { SearchBar } from './components/SearchBar'
import { SortControl } from './components/SortControl'
import { SquadToggle } from './components/SquadToggle'
import { searchPlayers } from './lib/searchPlayers'
import { sortPlayers } from './lib/sortPlayers'
import { TEAM } from './team'
import { SQUAD_LABELS, type Roster, type SortDirection, type SortKey, type Squad } from './types'

type RosterState = { status: 'loading' } | { status: 'error' } | { status: 'ready'; roster: Roster }

// The freshman roster gets its own URL (#freshman) so it can be shared or bookmarked.
const FRESHMAN_HASH = '#freshman'

function App() {
  const [rosterState, setRosterState] = useState<RosterState>({ status: 'loading' })
  const [squad, setSquad] = useState<Squad>(() => (window.location.hash === FRESHMAN_HASH ? 'freshman' : 'varsityJv'))
  const [query, setQuery] = useState('')
  const [sortKey, setSortKey] = useState<SortKey>('jersey')
  const [direction, setDirection] = useState<SortDirection>('asc')

  useEffect(() => {
    // roster.json is generated by scripts/build-roster.ts and served from public/
    fetch(`${import.meta.env.BASE_URL}roster.json`)
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`)
        return response.json() as Promise<Roster>
      })
      .then((roster) => setRosterState({ status: 'ready', roster }))
      .catch(() => setRosterState({ status: 'error' }))
  }, [])

  const allPlayers = useMemo(
    () => (rosterState.status === 'ready' ? rosterState.roster[squad] : []),
    [rosterState, squad],
  )

  function handleSquadChange(next: Squad) {
    setSquad(next)
    const url = next === 'freshman' ? FRESHMAN_HASH : window.location.pathname + window.location.search
    window.history.replaceState(null, '', url)
  }
  const players = useMemo(
    () => sortPlayers(searchPlayers(allPlayers, query), sortKey, direction),
    [allPlayers, query, sortKey, direction],
  )

  function handleSortChange(key: SortKey) {
    if (key === sortKey) {
      setDirection((current) => (current === 'asc' ? 'desc' : 'asc'))
    } else {
      setSortKey(key)
      setDirection('asc')
    }
  }

  return (
    <div className="app">
      <header className="app-header">
        <div className="brand">
          <span className="brand-logo">
            <img src={wildcatLogo} alt={`${TEAM.name} logo`} width="256" height="256" />
          </span>
          <div className="brand-text">
            <p className="brand-school">{TEAM.school}</p>
            <h1>
              {TEAM.name} <span className="brand-sport">{TEAM.sport}</span>
            </h1>
            <p className="brand-location">{TEAM.location}</p>
          </div>
        </div>
      </header>
      <div className="controls">
        <SquadToggle squad={squad} onChange={handleSquadChange} />
        <SearchBar value={query} onChange={setQuery} />
        <SortControl sortKey={sortKey} direction={direction} onChange={handleSortChange} />
      </div>
      <main>
        {rosterState.status === 'loading' && <p className="status">Loading roster…</p>}
        {rosterState.status === 'error' && (
          <p className="status">Couldn't load the roster. Check your connection and refresh.</p>
        )}
        {rosterState.status === 'ready' && allPlayers.length === 0 && (
          <p className="status">The {SQUAD_LABELS[squad]} roster isn't available yet.</p>
        )}
        {rosterState.status === 'ready' && allPlayers.length > 0 && (
          <>
            <p className="result-count" aria-live="polite">
              {SQUAD_LABELS[squad]}: {players.length} of {allPlayers.length} players
            </p>
            <RosterList players={players} />
          </>
        )}
      </main>
    </div>
  )
}

export default App
